import { contraMultiplier } from './contra.js';
import { pairOf } from './partnership.js';
export function contractValue(contract) {
    return { three: 1, two: 2, one: 3, solo: 4 }[contract];
}
export function declaredFigureValue(type) {
    return {
        tarokk8: 1,
        tarokk9: 2,
        tuletroa: 2,
        fourKings: 2,
        doubleGame: 4,
        volat: 6,
        // XXI-fogás: 60 points when declared; its silent value is 30 (half).
        xxiFogas: 60,
        centrum: 10,
        kismadar: 10,
        nagymadar: 10,
        pagatUltimo: 10,
        pagatUhu: 20,
        sasUltimo: 10,
        sasUhu: 20,
        kingUltimo: 15,
        kingUhu: 25,
    }[type];
}
export function silentFigureValue(type) {
    const value = declaredFigureValue(type);
    if (value === undefined)
        return undefined;
    if (type === 'tarokk8' || type === 'tarokk9' || type === 'centrum' || type === 'kismadar' || type === 'nagymadar' || type === 'pagatUhu' || type === 'sasUhu' || type === 'kingUhu')
        return undefined;
    return Math.floor(value / 2);
}
/**
 * Converts the declaration lifecycle into the concrete figure list consumed
 * by settlement. Failed declarations are included as losing figures; silent
 * figures generated by the locked-card rules are included automatically.
 */
export function figureSettlementsFromProgress(progress, takerId, partnerId) {
    const result = [];
    for (const declaration of progress.declarations) {
        if (declaration.type === 'tarokk8' || declaration.type === 'tarokk9')
            continue;
        const points = declaredFigureValue(declaration.type);
        if (points === undefined)
            continue;
        if (declaration.status !== 'fulfilled' && declaration.status !== 'failed')
            continue;
        const ownerPairWon = declaration.status === 'fulfilled';
        const ownerIsTakerPair = pairOf(declaration.ownerId, takerId, partnerId) === 'taker';
        result.push({
            type: declaration.type,
            points,
            ownerPairWon,
            ownerIsTakerPair,
            multiplier: contraMultiplier(declaration.contra.level),
            ...(declaration.silent ? { silent: true } : {}),
        });
    }
    for (const silent of progress.silentFigures) {
        const points = silentFigureValue(silent.type);
        if (points === undefined)
            continue;
        const ownerIsTakerPair = pairOf(silent.ownerId, takerId, partnerId) === 'taker';
        result.push({
            type: silent.type,
            points,
            ownerPairWon: silent.status === 'fulfilled',
            silent: true,
            ownerIsTakerPair,
        });
    }
    return result;
}
export function gameMultiplier(level) {
    return contraMultiplier(level);
}
/**
 * Scores the special game / double-game / volát component.
 *
 * The ordinary game is outcome-dependent. If neither double nor volát was
 * declared, only the highest applicable outcome is paid. A declared double
 * or volát has its own stake; when the declared double is lost, the opponent
 * also receives the ordinary game value. These rules follow the published
 * Illusztrált settlement table rather than treating double/volát as ordinary
 * independent figures.
 */
function gameLines(input) {
    const base = contractValue(input.contract);
    const trickPoints = input.takerTrickPoints ?? 0;
    const takerPairPoints = trickPoints + (input.takerSkartPoints ?? 0);
    const defencePoints = 94 - takerPairPoints;
    const takerWonAll = input.takerPairVolat === true;
    const defenceWonAll = input.defencePairVolat === true;
    const double = input.figures.find(f => f.type === 'doubleGame' && !f.silent);
    const volat = input.figures.find(f => f.type === 'volat' && !f.silent);
    const multiplier = gameMultiplier(input.gameContra);
    const lines = [];
    // A declared double and a declared volát are independent figures: if both
    // were announced and fulfilled, both are paid. The published Illusztrált
    // guidance explicitly permits saying both together.
    if (double) {
        // A declared figure has its own contra chain. The game-level contra is
        // only the multiplier of the ordinary game stake.
        const doubleMultiplier = double.multiplier ?? 1;
        lines.push({
            kind: 'figure', type: 'doubleGame', points: base * 4 * doubleMultiplier,
            positiveForTakerPair: double.ownerIsTakerPair === undefined
                ? double.ownerPairWon
                : double.ownerIsTakerPair === double.ownerPairWon,
        });
    }
    if (volat) {
        // A declared Volát has a 6-point nominal figure value.  Without its own
        // contra chain the losing declaration carries the traditional 3x figure
        // settlement; once an explicit figure-contra is present, that chain is
        // authoritative and its multiplier replaces the default settlement.
        const volatPoints = volat.multiplier !== undefined
            ? 6 * (base === 2 ? 2 : 1) * volat.multiplier
            : 6 * base;
        lines.push({
            kind: 'figure', type: 'volat', points: volatPoints,
            positiveForTakerPair: volat.ownerIsTakerPair === undefined
                ? volat.ownerPairWon
                : volat.ownerIsTakerPair === volat.ownerPairWon,
        });
    }
    // A declared double / volát is itself the game stake for that declaration.
    // It therefore replaces the ordinary game line; if it fails, the same
    // declared value is paid to the opposing side rather than adding another
    // ordinary-game charge.
    if (double || volat)
        return lines;
    if (input.takerTrickPoints === undefined) {
        return [{
                kind: 'game', points: base * multiplier,
                positiveForTakerPair: input.takerPairWon,
            }];
    }
    // Silent volát depends only on who took all tricks, NOT on point value.
    // Skart composition is therefore irrelevant for volát.
    if (takerWonAll) {
        return [{ kind: 'figure', type: 'volat', points: base * 3 * multiplier, positiveForTakerPair: true }];
    }
    if (defenceWonAll) {
        return [{ kind: 'figure', type: 'volat', points: base * 3 * multiplier, positiveForTakerPair: false }];
    }
    // Silent double uses the pair's total point value. All three non-taker
    // skarts belong to the defence, including the taker partner's skart.
    if (takerPairPoints >= 71) {
        return [{ kind: 'figure', type: 'doubleGame', points: base * 2 * multiplier, positiveForTakerPair: true }];
    }
    if (defencePoints >= 71) {
        return [{ kind: 'figure', type: 'doubleGame', points: base * 2 * multiplier, positiveForTakerPair: false }];
    }
    // Ordinary game: the taker pair wins at 48+, otherwise the defence wins.
    return [{
            kind: 'game', points: base * multiplier,
            positiveForTakerPair: input.takerPairWon,
        }];
}
export function settlementLines(input) {
    const lines = gameLines(input);
    const hasExplicitDouble = input.figures.some(f => f.type === 'doubleGame' && !f.silent);
    const hasExplicitVolat = input.figures.some(f => f.type === 'volat' && !f.silent);
    const silentVolat = !hasExplicitDouble && !hasExplicitVolat && (input.takerPairVolat === true || input.defencePairVolat === true);
    const silentDouble = !hasExplicitDouble && !hasExplicitVolat && (input.takerTrickPoints !== undefined) && (((input.takerTrickPoints ?? 0) + (input.takerSkartPoints ?? 0) >= 71) || ((94 - ((input.takerTrickPoints ?? 0) + (input.takerSkartPoints ?? 0))) >= 71));
    for (const figure of input.figures) {
        if (figure.type === 'doubleGame' || figure.type === 'volat')
            continue;
        if (figure.silent && (silentVolat || silentDouble) && (figure.type === 'tuletroa' || figure.type === 'fourKings'))
            continue;
        const multiplier = figure.multiplier ?? 1;
        const silentBase = figure.silent ? silentFigureValue(figure.type) : undefined;
    const effectivePoints = figure.silent
      ? (silentBase !== undefined && figure.points <= silentBase ? figure.points : Math.floor(figure.points / 2))
      : figure.points;
        lines.push({
            kind: 'figure',
            type: figure.type,
            points: effectivePoints * multiplier,
            positiveForTakerPair: figure.ownerIsTakerPair === undefined
                ? figure.ownerPairWon
                : (figure.ownerIsTakerPair === figure.ownerPairWon),
            ...(figure.silent ? { silent: true } : {}),
        });
    }
    return lines;
}
export function settlementComponents(input) {
    return settlementLines(input).reduce((sum, line) => sum + (line.positiveForTakerPair ? line.points : -line.points), 0);
}
/**
 * Returns a complete, UI-friendly settlement without losing the individual
 * figure lines. A positive net belongs to the taker pair; a negative net
 * belongs to the defence.
 */
export function calculateSettlement(input) {
    const lines = settlementLines(input);
    const netForTakerPair = lines.reduce((sum, line) => sum + (line.positiveForTakerPair ? line.points : -line.points), 0);
    const takerPairPoints = (input.takerTrickPoints ?? 0) + (input.takerSkartPoints ?? 0);
    return {
        lines,
        takerPairPoints,
        defencePairPoints: 94 - takerPairPoints,
        netForTakerPair,
        gameWonBy: input.takerPairWon ? 'taker' : 'defence',
    };
}
